### PR TITLE
Fixing .b64EncodeFile() core dump

### PR DESCRIPTION
**Pull request by HenrikBengtsson**

### CODE REVIEW

**Comment by yihui** [comment]
Thanks a lot! I'm not a C expert, so I'm wondering if @jjallaire or @jeffreyhorner could review it.

BTW, we will also need a contributor agreement from you: https://github.com/rstudio/rmarkdown/blob/master/CONTRIBUTING.md

**Comment by HenrikBengtsson** [comment]
Now the new test passes on Travis CI.

Honestly, I prefer not to sign anything too general. Having said this, I do hereby give the copy-right holder of the `markdown` package all the rights (including copy rights) to the contributions part of this pull request.

Also, may I suggest that the copyright holder of the package is explicitly specified in the DESCRIPTION file using the `Authors@R` field and the `cph` tag?  Not that it matter, but I was under the impression that this is @jeffreyhorner's package.

**Comment by jjallaire** [comment]
This change looks good to me.

Very good point on using Authors@R. @jeffreyhorner originally wrote the package on contract with RStudio so we are indeed the copyright holders. @yihui, the note from Henrik above regarding copyright assignment is fine lieu of the standard contributor agreement.

**Comment by yihui** [comment]
I have changed `Author` to `Authors@R`. Thanks!

**Comment by HenrikBengtsson** [comment]
Thanks for the clarifications and thanks for incorporating this.

**Pull request merged**
